///|
fn main {
  println("00. パタトクカシーー")
  println(@src.e_00())
  println(@src.e_00_2())
  println(@src.e_00_3())
  println(@src.e_00_4())
  println(@src.e_00_5())
  println(@src.e_00_6())
  println("01. タクシー")
  println(@src.e_01())
  println(@src.e_01_2())
  println("02. 文字列の逆順")
  println(@src.e_02())
  println("03. 円周率")
  @debug.debug(@src.e_03())
  println("04. 元素記号")
  @debug.debug(@src.e_04())
}
